// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-client-angular
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-description: Explore how to access a simple RESTful web service and consume its resources with Angular in Open Liberty.
:page-essential: false
:page-guide-catagory: none
:page-permalink: /guides/{projectid}
:page-releasedate: 2019-04-26
:page-related-guides: ['rest-intro', 'rest-client-java']
:page-seo-title: Consuming RESTful web services with Angular
:page-seo-description: A tutorial on how to consume your microservices with Angular
:page-tags: ['Java EE']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Consuming a RESTful web service with Angular

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to access a simple RESTful web service and consume its resources with Angular in Open
Liberty.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

https://angular.io[Angular^] is a framework for creating interactive web applications.
Angular applications are written in HTML, CSS, and
https://www.typescriptlang.org[TypeScript^], a variant of JavaScript. Angular helps you
create responsive and intuitive applications that download once and run as a single web
page. Consuming REST services with your Angular application allows you to request
only the data and operations you need, minimizing loading times.

You'll learn how to access a REST service and deserialize the returned JSON that
contains a list of artists and their albums by using an Angular service and the Angular
HTTP Client. You'll present this data using an Angular component.

The REST service that provides the artists and albums resource was written for you in
advance and responds with the [hotspot]`artists.json`.

The Angular application has been created and configured for you in the `frontend`
directory. It contains the default starter application. There are many files that make
up an Angular application, but you only need to edit a few to consume the REST service
and display its data.

Angular applications must be compiled before they can be used. The Angular compilation
step has been configured as part of the Maven build. You can use the `start` folder of
this guide as a template for getting started with your own applications built on
Angular and Open Liberty.

artists.json
[source, json, linenums, role="code_column"]
----
include::finish/src/resources/artists.json[]
----

You will implement an Angular client that consumes this JSON and displays its contents at the
following URL: `\http://localhost:9080/app`.

To learn more about REST services and how you can write them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^].


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Starting the service
// =================================================================================================

== Starting the service

Before you begin the implementation, start the provided REST service so that
the artist JSON is available to you.

To start the REST service, navigate to the `start` directory and run the Maven
`install` and `liberty:start-server` goals:

[role='command']
----
mvn install liberty:start-server
----

After you start the server, you can find your artist JSON at
the following URL: http://localhost:9080/artists[http://localhost:9080/artists^].

You can rebuild the front end at any time. To do so, run Maven with the
`generate-resources` goal:
[role='command']
----
mvn generate-resources
----

Any local changes to your TypeScript and HTML are picked up when you build the
front end. After you start the Open Liberty server, you don't need to restart it.


// =================================================================================================
// Guide
// =================================================================================================

== Importing the HTTP client

Navigate to the `start` directory to begin.

Your application will need some way of communicating with RESTful web services in order
to retrieve their resources. In the case of this guide, the provided Angular
application will need to communicate with the artists service to retrieve the artists
JSON. While there are various ways of doing this, Angular contains a built-in HTTP
Client module that you can use.

Begin by importing the Angular HTTP Client module into the root module.

app.module.ts
[source, javascript, linenums, role="code_column"]
----
include::finish/src/main/frontend/src/app/app.module.ts[tags=**]
----

Angular applications consist of modules, which are groups of classes that
perform a specific function. The Angular framework provides its own modules
for applications to use. One of these, the HTTP Client module, includes convenience
classes that will make it easier and quicker for you to consume a RESTful API from
your application.

The provided application is organized into a module, called the root module and defined
in [hotspot]`app.module.ts`. You must import the HTTP Client module into the root
module in order for its classes to be accessible from the application's code.

[role="code_command hotspot", subs="quotes"]
----
#Update the `app.module.ts` file.#
`src/main/frontend/src/app/app.module.ts`
----
[role="edit_command_text"]
Import the [hotspot=3]`HttpClientModule` class into the file, then update the
[hotspot=11-14]`imports` array within the [hotspot=7-17]`@NgModule` declaration to
include [hotspot=13]`HttpClientModule`.

== Creating the Angular component

You will need to create the component used in the application to acquire and display
data from the REST API. The component file will contain two classes: the service, which
will handle data access, and the component itself, which will handle presenting the
data. The provided Angular application already contains a component.

app.component.ts
[source, javascript, linenums, role="code_column"]
----
include::finish/src/main/frontend/src/app/app.component.ts[tags=**]
----

=== Defining a service to fetch data

Services are classes in Angular that are designed to share their functionality across
the entire application. A good service performs only one function and does it well. In
this case, `ArtistsService` will handle requesting artists data from the REST
application.

[role="code_command hotspot", subs="quotes"]
----
#Update the `app.component.ts` file.#
`src/main/frontend/src/app/app.component.ts`
----
[role="edit_command_text"]
Create the entire [hotspot=5-19]`ArtistsService` class. Add the [hotspot=2]`HttpClient`
and [hotspot=3]`Injectable` import statements at the top.

The file imports the [hotspot=2]`HttpClient` and [hotspot=3]`Injectable`.

The [hotspot=5-19]`ArtistsService` class is defined. While it shares the same file as
the component class [hotspot=27]`AppComponent`, it can also be defined in its own file.
The class is annotated [hotspot=5]`@Injectable` so instances of it can be provided to
other classes anywhere in the application.

The class injects an instance of the [hotspot=7]`HttpClient` class, which it will use to
request data from the REST API. It contains a constant [hotspot=9]`ARTISTS_URL` which
points to the API endpoint it will request data from. Finally, it implements a method
[hotspot=11-18]`fetchArtists()` that makes the request and returns the result.

To obtain the data for display on the page, [hotspot=11-18]`fetchArtists()` tries to use the
injected [hotspot=13]`http` instance to perform a `GET` HTTP request to the
[hotspot=9]`ARTISTS_URL` and returning the result. If an error occurs, it prints the
message of the error to the console.

[hotspot=11-18]`fetchArtists()` uses a feature of Javascript called
[hotspot=11]`async` and [hotspot=13]`await` to make the request and receive the
response without preventing the application from working while it waits. In order to be
compatible with this feature, the result of the [hotspot=13]`HttpClient.get()` method
must be converted to a Promise using [hotspot=13]`toPromise()`.

=== Defining a component to consume a service

Components are the basic building block of Angular application user interfaces.
Components are made up of a Typescript class annotated with the
[hotspot=21-26]`@Component` annotation and the HTML template file (specified by
[hotspot=23]`templateUrl`) and CSS style files (specified by [hotspot=25]`styleUrls`.) 

Update the [hotspot=21-37]`AppComponent` class to use the artists service to fetch the
artists data and save it so the component can display it.

[role="code_command hotspot", subs="quotes"]
----
#Update the `app.component.ts` file.#
`src/main/frontend/src/app/app.component.ts`
----
[role="edit_command_text"]
Replace the entire [hotspot=21-37]`AppComponent` class as shown. Add
[hotspot=1]`OnInit` to the list of imported classes at the top.

The [hotspot=24]`providers` property on the [hotspot=21-26]`@Component` annotation
indicates that this component provides the [hotspot=5-19]`ArtistsService` to other
classes in the application.

`AppComponent` implements [hotspot=27]`OnInit`, which is a special interface called a 
lifecycle hook. When Angular displays, updates, or removes a component, it calls a
specific function on the component&mdash;the lifecycle hook&mdash;so the component can
run code in response to this event. This component responds to the [hotspot=27]`OnInit`
event via the [hotspot=32]`ngOnInit` method to fetch and populate its template with
data when the component is initialized for display. The file imports the
[hotspot=1]`OnInit` interface from the [hotspot=1]`@angular/core` package. The
[hotspot=27]`AppComponent` class implements the [hotspot=27]`OnInit` interface.

[hotspot=28]`artists` is a class member of type `any[]` that starts out as an empty
array. It holds the artists retrieved from the service so the template can
display them.

An instance of the [hotspot=30]`ArtistsService` class is injected into the constructor
and is accessible by any function defined in the class. The [hotspot=32-36]`ngOnInit`
function uses the [hotspot=33]`artistsService` instance to request the artists data.
Since [hotspot=11-18]`fetchArtists()` is an `async` function, it returns a Promise. To
retrieve the data from the request, [hotspot=32-36]`ngOnInit` calls
[hotspot=33-35]`then()` on the Promise and provides a function that takes in the data
and stores it to the [hotspot=28]`artists` class member.

== Creating the Angular component template

Now that you are have a service to fetch the data and a component to store it in, you
will create a template to specify how the data will be displayed on the page. When you
visit the page in the browser, the component will populate the template to display
the artists data with formatting.

[role="code_command hotspot", subs="quotes"]
----
#Replace the component's template file `app.component.html`.#
`src/main/frontend/src/app/app.component.html`
----

app.component.html
[source, html, linenums, role="code_column"]
----
include::finish/src/main/frontend/src/app/app.component.html[tags=**]
----

The template contains a [hotspot=1]`div` that is enumerated using `*ngFor`. The
`artists` variable is bound to the `artists` member of the component. The div itself
and all elements contained within it are repeated for each artist, and the
[hotspot=2]`{{ artist.name }}` and `{{ artist.albums.length }}` placeholders are
populated with the information from each artist. The same strategy is used to display
each [hotspot=3]`album` by each artist.

The Open Liberty server is already started, and the REST service is running. You can
recompile the front end by running the following command:
[role='command']
```
mvn generate-resources
```

Then point your browser to the web application root
http://localhost:9080/app[http://localhost:9080/app^] to see the following output:

[subs="quotes", role="no_copy"]
----
foo wrote 2 albums:
    Album titled *album_one* by *foo* contains *12* tracks
    Album tilted *album_two* by *foo* contains *15* tracks
bar wrote 1 albums:
    Album titled *foo walks into a bar* by *bar* contains *12* tracks
dj wrote 0 albums:
----


== Testing the Angular client

No explicit code directly uses the consumed artist JSON, so you don't need to write
any test cases for this guide.

Whenever you change and build your Angular implementation, the application root at
http://localhost:9080/app[http://localhost:9080/app^] will
reflect the changes automatically. You can visit the root to manually check whether
the artist JSON was consumed correctly. You can rebuild only your Angular frontend by
running the following command:
[role='command']
```
mvn generate-resources
```

When you are done checking the application root, stop the Open Liberty server by
running the following command:
[role='command']
```
mvn liberty:stop-server
```

Although this guide didn't teach you how to build logic, you will likely build logic
when you develop your own applications, and testing will become a crucial part of your
development lifecycle. If you need to write test cases, follow the official unit
testing and end-to-end testing documentation on the
https://angular.io/guide/testing[official Angular page^].



== Great work! You're done!

You have just accessed a simple RESTful web service and consumed its resources using
Angular in Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
